### ISSUE TITLE
pass in `--color` flag

### ISSUE THREAD

**Issue by princejoogie** [samodostal/image.nvim#1]
`ascii-image-converter` can accept --color ([here](https://github.com/TheZoraiz/ascii-image-converter#--color-or--c)) to support colors in the output. is there any way we can have that in the setup?

**Comment by samodostal** [comment]
I was also thinking about that but I don't think it is possible without changing how rendering works now. Right now the text is inserted into a buffer which I don't think supports changing colors for specific characters.

However, this could work if we would open a terminal inside neovim with `:term` and call the `ascii-image-converter` with `--color` there. When I tried it this worked but I think it would create some more issues with image centering and buffers, for example nvim-tree not highlighting selected image as the terminal buffer is completely different from the image buffer.

I will look into this more. Thanks for the suggestion!

**Comment by max397574** [comment]
changing colors for specific characters is possible
`:h nvim_buf_add_highlight`

**Comment by samodostal** [comment]
That looks promising! Will try to implement it. If the performance takes too much of a hit though it could be an option disabled by default. Thanks for sharing this!

**Comment by max397574** [comment]
would be really cool if you'd be able to do this
I think you'd "only" have to write a function to parse the terminal color codes into colors and then remove them

**Comment by max397574** [comment]
@samodostal any progress on this?

**Comment by samodostal** [comment]
I did some work on this about a month ago but didn't have time to continue on it recently. I pushed some WIP code to a branch `feature/1-colors`. If you would like to continue where I left off I would be happy to merge it afterward. If not I'll look into it soon-ish.

**Comment by Slotos** [comment]
With https://github.com/m00qek/baleia.nvim virtually no extra work is to be done (except for checking its presence, of course).

```diff
diff --git a/lua/image/api/init.lua b/lua/image/api/init.lua
index bbfe9b2..7866b19 100644
--- a/lua/image/api/init.lua
+++ b/lua/image/api/init.lua
@@ -5,9 +5,9 @@ local M = {}
 M.get_ascii_data_sync = function(buf_path, ascii_width, ascii_height, opts, callback)
        local command = nil
        if opts.render.use_dither then
-               command = { "ascii-image-converter", buf_path, "-b", "--dither", "-d", ascii_width .. "," .. ascii_height }
+               command = { "ascii-image-converter", buf_path, "-C", "-b", "--dither", "-d", ascii_width .. "," .. ascii_height }
        else
-               command = { "ascii-image-converter", buf_path, "-d", ascii_width .. "," .. ascii_height }
+               command = { "ascii-image-converter", buf_path, "-C", "-d", ascii_width .. "," .. ascii_height }
        end
 
        vim.fn.jobstart(command, {
diff --git a/lua/image/ui/init.lua b/lua/image/ui/init.lua
index ba89828..91e9ccc 100644
--- a/lua/image/ui/init.lua
+++ b/lua/image/ui/init.lua
@@ -40,7 +40,9 @@ M.buf_insert_data_with_padding = function(buf_id, data, horizontal_padding, vert
 
        insert_blank_lines(data_with_padding, vertical_padding - 2)
 
-       vim.api.nvim_buf_set_lines(buf_id, 0, -1, false, data_with_padding)
+       local baleia = require('baleia').setup { }
+       baleia.buf_set_lines(buf_id, 0, -1, false, data_with_padding)
 end
 
 return M
```

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/314453/196168423-b53e202e-850e-45c1-b3ed-203d7e7b1454.png">

**Comment by samodostal** [comment]
Wow, what a nice find! I'll merge this today. There will have to be an option for this though so only people that want colors have to install an additional plugin. Thanks for this!
