### ISSUE TITLE
No image shown

### ISSUE THREAD

**Issue by WhiteBlackGoose** [samodostal/image.nvim#8]
Hello. Trying to use this great plugin, but can't get it work. Just no ASCII image shown, and no error, nothing

![image](https://user-images.githubusercontent.com/31178401/203276002-ccbf9e51-995d-46f6-9c0e-9a268837ca96.png)

Setting up (installed the deps)
```
Plug 'samodostal/image.nvim'
```

setup
```
require('image').setup {
  render = {
    min_padding = 5,
    show_label = true,
    use_dither = false,
    foreground_color = true,
    background_color = true
  },
  events = {
    update_on_nvim_resize = true,
  },
}

```
(tried disabling foreground_color and background_color)

**Comment by samodostal** [comment]
Hey, your setup looks correct but I have some ideas that might help:
1. Try using the `ascii-image-converter` from your terminal to see if that works.
2. Make sure the image file is a valid image
3. Make sure the `require('image')` is actually being called (e.g. print something a line before)
4. You can try to disable colors and go with the default settings first.

Let me know if the issue still persists!

**Comment by WhiteBlackGoose** [comment]
Hi, thanks for quick response!

1. It works
2. It is
3. Yes, it gets called. Checked with print just in case
4. Same thing :cry: 

NVIM v0.8.0-1210-gd367ed9b2

**Comment by samodostal** [comment]
Looks like this issue occurs with the newest version of `ascii-image-converter:v1.13.0`. I upgraded to the newest version and I see the same empty screen

**Comment by WhiteBlackGoose** [comment]
Yeah I have the same version

**Comment by TheZoraiz** [comment]
Just released ascii-image-converter `v1.13.1` that should fix this issue

**Comment by samodostal** [comment]
Awesome, it works now. Thanks a lot!

**Comment by WhiteBlackGoose** [comment]
Thank you so much, it works
