### ISSUE TITLE
Close window after losing focus ?

### ISSUE THREAD

**Issue by Curs3W4ll** [samodostal/image.nvim#9]
Your plugin is working good as hell, but juste one thing that is annoying me.

When we open another file when being in an image preview window, this does not close the image preview window.

It will be cool that, when we open another file/buffer, the image preview window closes itself when opening something else.

not necessarily closing the buffer, but at least the window.

**Comment by samodostal** [comment]
Unless I misunderstood your message, this is not the thing I am experiencing.
When I open an image (let's call it image1.png) I see the image in the focused window, as intended. Then I open image2.png and in the same window image2.png gets opened (Or any other file for that matter).

So basically there is only one window filled with the corresponding buffer. You can also see the behavior in the gif inside the readme file of this repo.

Maybe try opening the second image directly with the `:e` command while being focused on the correct window and it might work as intended. If it does work, then the problem might be in the way you are opening the second image. If not then there might be an underlying issue in this plugin.

Let me know if this helps :)

**Comment by Curs3W4ll** [comment]
Thanks for the response,

This might be in my config then, I probably will post the solution inside this issue when I found it.

Sorry for the inconvenience, I'm closing this issue for now on and I will comment later.
